changed boost interprocess to date_time + include deque
machines-in-motion/shared_memory pull request #36
Opened 2024-01-26 16:17 UTC by skleff1994

This PR fixes bug due to deprecated boost version

2024-01-29 08:40 UTC, MaximilienNaveau requested changes
@vincentberenz Could you double check this ?

2024-01-29 08:40 UTC, MaximilienNaveau commented on include/shared_memory/condition_variable.hpp
> +#include <boost/date_time/microsec_time_clock.hpp>
I would put these includes inside the cpp files directly.
The header does need them directly.

2024-01-29 08:40 UTC, MaximilienNaveau commented on include/shared_memory/internal/exchange_manager_memory.hpp
> +#include <deque>
See comments about headers.
And why do you need the deque here? you are not using it yes?

2024-01-29 08:40 UTC, MaximilienNaveau commented on include/shared_memory/locked_condition_variable.hpp
> +#include <boost/date_time/microsec_time_clock.hpp>
Follow comments about the headers

2024-01-29 08:40 UTC, MaximilienNaveau commented on src/condition_variable.cpp
> +        boost::date_time::microsec_clock<boost::posix_time::ptime>::universal_time();
Thanks for the maintenance

2024-01-30 12:32 UTC, vincentberenz commented on include/shared_memory/condition_variable.hpp
> +#include <boost/date_time/microsec_time_clock.hpp>
So far we were putting all includes in the header file ... I'd keep it this way

2024-01-30 12:32 UTC, vincentberenz commented on src/condition_variable.cpp
> +        boost::date_time::microsec_clock<boost::posix_time::ptime>::universal_time();
Thanks as well ! You confirm the unit tests still pass ?

2024-08-08 21:36 UTC, skleff1994 commented on include/shared_memory/internal/exchange_manager_memory.hpp
> +#include <deque>
deque is actually used in the .hxx

2024-08-08 21:40 UTC, skleff1994 commented on src/condition_variable.cpp
> +        boost::date_time::microsec_clock<boost::posix_time::ptime>::universal_time();
Thank you for your review @MaximilienNaveau  @vincentberenz  and apologies for my late reply

- @vincentberenz I checked that all unittests are still passing 
- @MaximilienNaveau I left all the includes in the headers, as suggested here https://github.com/machines-in-motion/shared_memory/pull/36#discussion_r1471133789 but I'm happy to put them in the .hxx if requested

2024-08-23 13:17 UTC, vincentberenz commented
@MaximilienNaveau I'd be ok merging, but looks like I do not have the rights. Or should @skleff1994 do it ?

2024-08-23 13:19 UTC, merged